name: Weekly GPS Update and Deploy to Shinyapps.io

on:
  schedule:
    - cron: '0 0 * * 1'  # runs once a week, every monday at midnight utc
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  update-gps-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up R 4.4.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Verify Quarto installation
        run: |
          quarto --version


      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libudunits2-dev gdal-bin
          
      - name: Install R packages
        run: |
          mkdir -p ~/R/library
          echo 'R_LIBS_USER="~/R/library"' >> ~/.Renviron
          Rscript -e "install.packages(c(
            'rnaturalearthdata', 'rnaturalearth', 'shiny', 'sf', 'cronR', 'move', 'dplyr',
            'purrr', 'data.table', 'zoo', 'lubridate', 'mapview', 's2', 'rsconnect',
            'leaflet', 'leaflet.extras', 'leafgl', 'terra', 'ggplot2','plotly','shinycssloaders'),
            repos='https://cloud.r-project.org', lib='~/R/library')"
      - name: Run import_location_data.R
        run: Rscript import_location_data.R

      - name: Run filter_location_data.R for Do単ana_Wetland_Viewer
        run: Rscript Do単ana_Wetland_Viewer/filter_location_data.R

      - name: Run filter_location_data.R for Friesland_GPI_App
        run: Rscript Friesland_GPI_App/filter_location_data.R

      - name: Run filter_location_data.R for Senegal_Delta_Habitat_Use_App
        run: Rscript Senegal_Delta_Habitat_Use_App/filter_location_data.R

      - name: Check R environment
        run: Rscript -e "sessionInfo()"

      - name: Deploy Do単ana_Wetland_Viewer to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::setAccountInfo(name = '${{ secrets.SHINYAPPS_ACCOUNT }}',
                                                token = '${{ secrets.SHINYAPPS_TOKEN }}',
                                                secret = '${{ secrets.SHINYAPPS_SECRET }}');
                      rsconnect::deployApp(appDir = 'Do単ana_Wetland_Viewer', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      - name: Deploy Friesland_GPI_App to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::deployApp(appDir = 'Friesland_GPI_App', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      - name: Deploy Senegal_Delta_Habitat_Use_App to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::deployApp(appDir = 'Senegal_Delta_Habitat_Use_App', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      - name: Deploy Flyway_Tracking_Summary_App to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::deployApp(appDir = 'Flyway_Tracking_Summary_App', quarto = NA, forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
